server:
  port: 8800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elsearch?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver # 连接池
    type: com.alibaba.druid.pool.DruidDataSource # 使用德鲁伊连接池
    druid:
      initial-size: 5 #初始化时建立物理连接的个数
      max-active: 20 #最大连接池数量
      min-idle: 5 #最小连接池数量
      max-wait: 3000 #获取连接时最大等待时间，单位毫秒
      pool-prepared-statement: false #是否缓存preparedStatement，也就是PSCache，PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      max-open-prepared-statements: -1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 300000
logging:
  level:
    root: info
    com.xhy.search: debug

elasticsearch:
  host: 106.55.180.191
  port: 9200
